version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql_commandas_api
    environment:
      MYSQL_ROOT_PASSWORD: abcBolinhas12345
      MYSQL_DATABASE: comandas_db
      MYSQL_USER: Michel
      MYSQL_PASSWORD: abcBolinhas12345
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: >
      bash -c "
      docker-entrypoint.sh mysqld &
      pid=\$!
      sleep 30 &&
      mysql -u root -pabcBolinhas12345 -e 'CREATE DATABASE IF NOT EXISTS comandas_db;'
      wait \$pid
      "

  api:
    image: comanda-api  # Essa imagem deve ser construída com o Dockerfile acima
    container_name: comandas_api
    depends_on:
      - db
    environment:
      # Ajuste as variáveis de ambiente da API para usar MySQL
      DB_SGDB: mysql
      DB_NAME: comandas_db
      DB_HOST: db:3306
      DB_USER: Michel
      DB_PASS: abcBolinhas12345
    ports:
      - "4443:4443"
    restart: always

volumes:
  db_data:
    driver: local
